import "./globals.css";
import type { Metadata } from "next";
import { Bebas } from "./Fonts/Fonts";
import Footer from "./component/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Bebas.className}>{children}</body>
      <Footer />
    </html>
  );
}
