import "./globals.css";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Bebas_Neue } from "next/font/google";

const Jarkarta = Plus_Jakarta_Sans({ subsets: ["latin"] });
const Bebas = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Jarkarta.className}>{children}</body>
    </html>
  );
}
